# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# Temporarily enable when caching package library.
script: true

language: r
cache: packages
sudo: false

matrix:
  include:
  - os: linux
    r: release
    warnings_are_errors: true
  - os: linux
    r: devel
    warnings_are_errors: true
  - os: osx
    r: release
    warnings_are_errors: true
  fast_finish: true

env:
  global:
    - LINTR_COMMENT_BOT=true

github_packages:
  - mjsteinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
