language: general

services:
  - docker

branches:
  only:
    - master

install:
  - rm -rf .Rcheck
  - git clone https://github.com/acidgenomics/Rcheck.git .Rcheck

jobs:
  include:
    - stage: test
      name: "bioc-3.9"
      script: image="basejump" tag="bioc-3.9" ./.Rcheck/docker
    - stage: test
      name: "bioc-3.8"
      script: image="basejump" tag="bioc-3.8" ./.Rcheck/docker
    - stage: test
      name: "bioc-3.7"
      script: image="basejump" tag="bioc-3.7" ./.Rcheck/docker
    - stage: test
      name: "bioc-devel"
      script: image="basejump" tag="bioc-devel" ./.Rcheck/docker

matrix:
  allow_failures:
    - name: "bioc-devel"
  fast_finish: true

after_failure:
  - ./.Rcheck/docker-failure

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
